### ISSUE TITLE
gym import fail 

### ISSUE THREAD

**Issue by OusmaneKana** [amir-Nau/MachineLearning#1]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0177af7e6204> in <module>
----> 1 import gym
      2 import numpy as np
      3 env = gym.make("MountainCar-v0")
      4 
      5 

ModuleNotFoundError: No module named 'gym'

>>I have gym installed through pip

**Comment by amir-Nau** [comment]
Try to use pip3 to install a gym.

**Comment by amir-Nau** [comment]
Or run as python3 <filename>
