### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BedirT** [amir-Nau/MachineLearning#2]
Any plans on adding some documentation?  @amir-Nau 

It could be helpful for the structure to be more readable. For example, I couldn't find where you implemented q-learning mentioned in the tag.

**Comment by amir-Nau** [comment]
Yes, you are right. I will work on it. Thanks!

**Comment by BedirT** [comment]
Any update on this?

**Comment by amir-Nau** [comment]
Hello Bedir, Thank you so much for the reminder. I have modified the purpose of this repository to a collection of projects on deep learning. I am currently researching RL and created a separate repository for that.  The link: https://github.com/amir-Nau/Reinforced-Learning. Would love to hear your feedbacks!
